# Generated by Django 4.0.6 on 2022-07-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_assigned',
            field=models.DateField(),
        ),
    ]
