# Generated by Django 4.0.6 on 2022-07-27 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
