# Generated by Django 4.0.6 on 2022-07-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocerys', models.CharField(max_length=30)),
                ('date_created', models.DateField()),
                ('date_completed', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
