# Generated by Django 4.0.6 on 2022-07-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='grocerys',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
