# Generated by Django 4.1 on 2022-08-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0002_types_remove_pokemon_types_pokemon_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon', to='pokeapp.types'),
        ),
    ]
