# Generated by Django 4.0.6 on 2022-07-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='created_date',
        ),
    ]
