# Generated by Django 4.0.6 on 2022-07-23 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_remove_groceryitem_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
