# Generated by Django 4.0.6 on 2022-08-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='test',
            new_name='text',
        ),
    ]
