# Generated by Django 4.0.6 on 2022-07-27 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_due',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
