# Generated by Django 4.0.6 on 2022-08-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/<django.db.models.fields.related.ForeignKey>/% Y/% m /%d'),
        ),
    ]
