# Generated by Django 4.0.6 on 2022-08-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.PROTECT, to='todos.priority'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.CharField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
