# Generated by Django 4.0.6 on 2022-08-04 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem_priority_alter_priority_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='todos.priority'),
        ),
    ]
