# Generated by Django 4.0.6 on 2022-08-04 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_priority_priority_alter_todoitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='priority',
        ),
        migrations.AddField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Other')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todos.priority'),
        ),
    ]
