# Generated by Django 4.0.6 on 2022-08-04 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_priority_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.PROTECT, to='todos.priority'),
        ),
    ]
