# Generated by Django 4.0.6 on 2022-08-04 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_priority_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Other')], default='other', max_length=15),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.PROTECT, to='todos.priority'),
        ),
    ]
