# Generated by Django 4.0.6 on 2022-08-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_priority_name_alter_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Other')], default='other', max_length=15, null=True),
        ),
    ]
