# Generated by Django 4.0.6 on 2022-08-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='upload'),
        ),
    ]
