# Generated by Django 4.1 on 2022-08-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='public',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
