# Generated by Django 4.0.6 on 2022-07-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now=True)),
                ('comp_date', models.DateField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
