# Generated by Django 4.0.6 on 2022-07-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_remove_groceryitem_comp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='comp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(null=True),
        ),
    ]
