# Generated by Django 4.0.6 on 2022-07-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_groceryitem_comp_date_groceryitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='comp_date',
            field=models.DateField(default=False, null=True),
        ),
    ]
