# Generated by Django 4.0.6 on 2022-07-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0004_alter_groceryitem_comp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='comp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
