# Generated by Django 4.0.6 on 2022-08-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_alter_groceryitem_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='completed_date',
        ),
    ]
