# Generated by Django 4.0.6 on 2022-08-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_remove_groceryitem_completed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='text_description',
            new_name='item_name',
        ),
    ]
