# Generated by Django 4.0.6 on 2022-08-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0004_rename_text_description_groceryitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
