# Generated by Django 4.0.6 on 2022-07-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='created_date',
            new_name='completed_date',
        ),
    ]
