# Generated by Django 4.0.6 on 2022-07-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='desciption',
            new_name='description',
        ),
    ]
