# Generated by Django 4.0.6 on 2022-07-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_rename_desciption_groceryitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(null=True),
        ),
    ]
