# Generated by Django 4.0.6 on 2022-07-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_alter_groceryitem_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='description',
            new_name='name',
        ),
    ]
