# Generated by Django 4.0.6 on 2022-07-24 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0004_rename_description_groceryitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(default=1, null=True)),
                ('grocerylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_list.grocerylist')),
            ],
        ),
        migrations.DeleteModel(
            name='GroceryItem',
        ),
    ]
