# Generated by Django 4.0.6 on 2022-07-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0006_rename_items_item_rename_status_grocerylist_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='complete',
            field=models.BooleanField(choices=[('Completed', 'Incomplete')], null=True),
        ),
    ]
