# Generated by Django 4.0.6 on 2022-07-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0008_alter_grocerylist_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='complete',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
