# Generated by Django 4.0.6 on 2022-07-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0009_remove_grocerylist_complete_grocerylist_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocerylist',
            options={'ordering': ['-created']},
        ),
    ]
