# Generated by Django 4.0.6 on 2022-07-31 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0012_alter_grocerylist_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='completed',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='grocerylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery_list.grocerylist'),
        ),
    ]
