# Generated by Django 4.0.6 on 2022-07-31 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0013_alter_grocerylist_completed_alter_item_grocerylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='grocerylist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery_list.grocerylist'),
        ),
    ]
