# Generated by Django 4.0.6 on 2022-08-04 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0014_alter_item_grocerylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='grocerylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_list.grocerylist'),
        ),
    ]
