# Generated by Django 4.0.6 on 2022-07-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='students', to='assignments.assignment'),
        ),
    ]
